id: P76BD74DB
initial_creation_type: input
source_metadata:
  title: Menlungpa Mikyö Dorje
  language: en
  description: 'Texts by and about Menlungpa Mikyö Dorje (sman lung pa mi bskyod rdo
    rje, b. 12th C.):'
  volume:
    4476f6736c4f43b1bbecfd1428538a78:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      parent: Prayers
created_at: '2022-03-01T00:45:15.177946'
last_modified_at: '2022-03-01T00:45:15.177952'
